name: ploggo-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - shapely
  - folium
  - scikit-learn
  - matplotlib
  - python-dotenv
  - requests
  - ipykernel
  - pip
  - pip:
      - scipy==1.17.1